import { ProjectData } from "./types";

const GITHUB_BASE = "https://github.com/jothish-blip/cybersecurity-portfolio/tree/main";

export const projects: ProjectData[] = [
  {
    id: "01",
    projectNumber: "01",
    title: "Professional Statement",
    description: "A formal professional statement detailing my background, focus, and continuous learning in cybersecurity.",
    category: "Professional",
    status: "Introduction",
    technologies: [],
    skills: ["Professional Communication", "Career Planning"],
    githubUrl: `${GITHUB_BASE}/01%20-%20Professional%20Statement`,
    readmeUrl: `${GITHUB_BASE}/01%20-%20Professional%20Statement/README.md`,
    featured: false,
    whyBuilt: "To articulate my journey and dedication to the cybersecurity field.",
    whatWorkedOn: "Drafting a professional summary that outlines my objectives and skill sets.",
    outcome: "A finalized statement used across professional profiles.",
    images: {
    cover: "/projects/01-professional-statement/cover-1.png",
},
  },
  {
    id: "02",
    projectNumber: "02",
    title: "Botium Toys Security Audit",
    description: "Comprehensive security audit and risk assessment for a fictional toy company.",
    category: "Audit & Compliance",
    status: "Security Audit",
    technologies: ["Risk Assessment", "NIST CSF"],
    skills: ["Security Auditing", "Compliance", "Vulnerability Management"],
    githubUrl: `${GITHUB_BASE}/02%20-%20Botium%20Toys%20Security%20Audit`,
    readmeUrl: `${GITHUB_BASE}/02%20-%20Botium%20Toys%20Security%20Audit/README.md`,
    featured: true,
    whyBuilt: "To demonstrate the ability to conduct a comprehensive security audit using established frameworks.",
    whatWorkedOn: "Analyzing current controls, identifying gaps against the NIST CSF, and drafting a report.",
    outcome: "Identified several critical vulnerabilities and provided actionable mitigation strategies." ,
    images: {
    cover: "/projects/02-botium-toys-security-audit/cover-1.png",
    }
  },
  {
    id: "03",
    projectNumber: "03",
    title: "Network Security Event Analysis",
    description: "Analysis of network security events to detect anomalies and potential threats.",
    category: "Network Security",
    status: "Network Analysis",
    technologies: ["Wireshark", "Network Analysis"],
    skills: ["Traffic Analysis", "Anomaly Detection", "Protocol Analysis"],
    githubUrl: `${GITHUB_BASE}/03%20-%20Network%20Security%20Event%20Analysis`,
    readmeUrl: `${GITHUB_BASE}/03%20-%20Network%20Security%20Event%20Analysis/README.md`,
    featured: true,
    whyBuilt: "To practice identifying malicious activities within network traffic captures.",
    whatWorkedOn: "Inspecting PCAP files, isolating suspicious packets, and documenting the attack vectors.",
    outcome: "Successfully identified a simulated network intrusion attempt.",
    images: {
    cover: "/projects/03-network-security-event-analysis/cover-1.png",
    }
  },
  {
    id: "04",
    projectNumber: "04",
    title: "Linux File Permissions",
    description: "Managing and auditing file permissions on a Linux system to enforce least privilege.",
    category: "System Administration",
    status: "Security Audit",
    technologies: ["Linux", "Bash"],
    skills: ["Access Control", "System Administration", "Security Hardening"],
    githubUrl: `${GITHUB_BASE}/04%20-%20%20Linux%20File%20Permissions`,
    readmeUrl: `${GITHUB_BASE}/04%20-%20%20Linux%20File%20Permissions/README.md`,
    featured: false,
    whyBuilt: "To enforce the principle of least privilege in a multi-user Linux environment.",
    whatWorkedOn: "Modifying file and directory permissions using chmod and chown, and auditing access.",
    outcome: "Secured sensitive files and ensured users had only the permissions necessary for their roles." ,
    images: {
    cover: "/projects/04-linux-file-permissions/cover-1.png",
    }
  },
  {
    id: "05",
    projectNumber: "05",
    title: "SQL Filtering Queries",
    description: "Writing complex SQL queries to filter and extract security-relevant data.",
    category: "Database Security",
    status: "Log Analysis",
    technologies: ["SQL"],
    skills: ["Data Extraction", "Querying", "Log Analysis"],
    githubUrl: `${GITHUB_BASE}/05%20-%20SQL%20Filtering%20Queries`,
    readmeUrl: `${GITHUB_BASE}/05%20-%20SQL%20Filtering%20Queries/README.md`,
    featured: false,
    whyBuilt: "To efficiently retrieve security logs and audit records from a relational database.",
    whatWorkedOn: "Crafting specific SQL queries to filter login attempts, administrative actions, and errors.",
    outcome: "Extracted actionable insights from raw database logs." ,
    images: {
    cover: "/projects/05-sql-filtering-queries/cover-1.png",
    }
  },
  {
    id: "06",
    projectNumber: "06",
    title: "Vulnerability Assessment",
    description: "Conducting a vulnerability assessment to discover and document system weaknesses.",
    category: "Vulnerability Management",
    status: "Detection Lab",
    technologies: ["Nmap", "CVSS"],
    skills: ["Vulnerability Scanning", "Risk Scoring", "Reporting"],
    githubUrl: `${GITHUB_BASE}/06%20-%20Vulnerability%20Assessment`,
    readmeUrl: `${GITHUB_BASE}/06%20-%20Vulnerability%20Assessment/README.md`,
    featured: true,
    whyBuilt: "To systematically identify and evaluate vulnerabilities in a target system.",
    whatWorkedOn: "Scanning networks, evaluating findings using CVSS, and prioritizing remediation.",
    outcome: "Delivered a comprehensive vulnerability report with remediation steps." ,
    images: {
    cover: "/projects/06-vulnerability-assessment/cover-1.png",
    }
  },
  {
    id: "07",
    projectNumber: "07",
    title: "Detection & Response",
    description: "A comprehensive collection of incident response projects, from packet analysis to playbook creation.",
    category: "Incident Response",
    status: "Collection",
    technologies: ["Wireshark", "TCPDump", "Suricata", "Incident Response"],
    skills: ["Threat Detection", "Log Analysis", "Playbook Creation", "Malware Investigation"],
    githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response`,
    readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/README.md`,
    featured: true,
    images: {
    cover: "/projects/07-detection-and-response/cover-7.png",
    },
    childProjects: [
      {
        id: "07.1",
        projectNumber: "07.1",
        title: "Incident Handler's Journal",
        description: "Initial documentation and tracking of an ongoing security incident.",
        technologies: ["Documentation"],
        skills: ["Incident Tracking", "Record Keeping"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.1%20-%20Incident%20Handler's%20Journal`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.1%20-%20Incident%20Handler's%20Journal/README.md`,
        images: {
          cover: "/projects/07-detection-and-response/07.1-incidents-handler-journal/cover-4.png",
        },
        outcome: "Established a clear timeline of events for the incident."
      },
      {
        id: "07.2",
        projectNumber: "07.2",
        title: "Wireshark Packet Analysis",
        description: "Deep dive into network traffic to identify malicious payloads and communication.",
        technologies: ["Wireshark"],
        skills: ["Packet Analysis", "Protocol Inspection"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.2%20-%20Wireshark%20Packet%20Analysis`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.2%20-%20Wireshark%20Packet%20Analysis/README.md`,
        images: {
          cover: "/projects/07-detection-and-response/07.2-wireshark-packet-analysis/cover-3.png",
        },
        outcome: "Identified the source and nature of the malicious network traffic."
      },
      {
        id: "07.3",
        projectNumber: "07.3",
        title: "TCPDump Packet Capture",
        description: "Capturing and analyzing raw network packets from the command line.",
        technologies: ["TCPDump", "Linux"],
        skills: ["Command Line Packet Capture", "Traffic Filtering"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.3%20-%20TCPDump%20Packet%20Capture`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.3%20-%20TCPDump%20Packet%20Capture/README.md`,
        images: {
          cover: "/projects/07-detection-and-response/07.3-tcpdump-packet-capture/cover-1.png",
        },
        outcome: "Successfully isolated specific traffic patterns indicating unauthorized access.",
      },
      {
        id: "07.4",
        projectNumber: "07.4",
        title: "Investigate a Suspicious File",
        description: "Analyzing a potentially malicious file to determine its behavior and origin.",
        technologies: ["File Analysis Tools"],
        skills: ["Malware Analysis", "File Hashing", "Static Analysis"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.4%20-%20Investigate%20a%20Suspicious%20File`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.4%20-%20Investigate%20a%20Suspicious%20File/README.md`,
        images: {
          cover: "/projects/07-detection-and-response/07.4-investigate-a-suspicious-file/cover-1.png",
        },
        outcome: "Determined the file was malicious and gathered IOCs."
      },
      {
        id: "07.5",
        projectNumber: "07.5",
        title: "Playbook to respond to a phishing incident",
        description: "Creating a structured playbook for handling future phishing attacks.",
        technologies: ["Playbook Frameworks"],
        skills: ["Process Documentation", "Incident Response Planning"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.5%20-%20Playbook%20to%20respond%20to%20a%20phishing%20incident`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.5%20-%20Playbook%20to%20respond%20to%20a%20phishing%20incident/README.md`,
        outcome: "Standardized the organizational response to phishing attempts." ,
        images: {
          cover: "/projects/07-detection-and-response/07.5-playbook-to-respond-to-a-phishing-incident/cover-1.png",
        },
      },
      {
        id: "07.6",
        projectNumber: "07.6",
        title: "Suricata Alert Analysis",
        description: "Reviewing and tuning Suricata IDS alerts to reduce false positives.",
        technologies: ["Suricata"],
        skills: ["IDS/IPS", "Alert Tuning", "Rule Management"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.6%20-%20Suricata%20Alert%20Analysis`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.6%20-%20Suricata%20Alert%20Analysis/README.md`,
        outcome: "Improved detection accuracy and reduced noise in the security alerts." ,
        images: {
          cover: "/projects/07-detection-and-response/07.6-suricata-alert-analysis/cover-1.png",
        },
      },
      {
        id: "07.7",
        projectNumber: "07.7",
        title: "Final Incident Handler's Journal",
        description: "Concluding the incident response process and summarizing findings.",
        technologies: ["Documentation"],
        skills: ["Post-Incident Review", "Reporting"],
        githubUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.7%20-%20Final%20Incident%20Handler's%20Journal`,
        readmeUrl: `${GITHUB_BASE}/07%20-%20Detection%20%26%20Response/07.7%20-%20Final%20Incident%20Handler's%20Journal/README.md`,
        outcome: "Produced a comprehensive final report detailing the incident lifecycle and lessons learned.",
        images: {
          cover: "/projects/07-detection-and-response/07.7-final-incident-handler-journal/cover-1.png",
        },
      }
    ],
    whyBuilt: "To demonstrate a complete lifecycle of detecting, investigating, and responding to security incidents.",
    whatWorkedOn: "Analyzing network packets, investigating files, writing playbooks, and tuning IDS rules.",
    outcome: "A robust portfolio of incident response techniques and documentation."
  },
  {
    id: "08",
    projectNumber: "08",
    title: "Algorithm for File Updates in Python",
    description: "Developing a Python script to automate the parsing and updating of security-related files.",
    category: "Automation & Scripting",
    status: "Automation",
    technologies: ["Python"],
    skills: ["Scripting", "File Parsing", "Automation"],
    githubUrl: `${GITHUB_BASE}/08%20-%20Algorithm%20for%20File%20Updates%20in%20Python`,
    readmeUrl: `${GITHUB_BASE}/08%20-%20Algorithm%20for%20File%20Updates%20in%20Python/README.md`,
    featured: true,
    whyBuilt: "To automate the tedious process of updating allow/deny lists in text files.",
    whatWorkedOn: "Writing a Python script using file I/O operations and string manipulation.",
    outcome: "Reduced manual update time and minimized human error in managing access lists.",
    images: {
    cover: "/projects/08-algorithm-for-file-updates-in-python/cover-3.png",
    }
  }
];
