ALTER TABLE public.portfolio_visitors
ADD COLUMN IF NOT EXISTS platform TEXT,
ADD COLUMN IF NOT EXISTS color_depth INTEGER,
ADD COLUMN IF NOT EXISTS asn TEXT,
ADD COLUMN IF NOT EXISTS manufacturer TEXT;
